# Site settings
title: Lin's World
description: I have nothing to say anymore.
keywords: Horizon, Fun
author: Lin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://linjie2019.github.io" # the base hostname & protocol for your site
