# Site settings
title: Lin's World
description: I have nothing to say anymore.
keywords: Modern, Fun
author: Lin
baseurl: "/linjie2019.github.io" # the subpath of your site, e.g. /blog/
url: "http://linjie2019.github.com" # the base hostname & protocol for your site
